app/models/book.py
import datetime

class Book :

  def __init__(self, title, author, pages, publish_date, description, isbn):
      self.title = title
      self.author = author
      self.pages = pages
      self.publish_date = publish_date
      self.description = description
      self.isbn = isbn
    
  def to_json(self):
      return {
        "title": self.title,
        "author": self.author,
        "pages": self.pages,
        "publish_date": datetime.datetime.strptime(str(self.publish_date), "%Y-%m-%d"),
        "description": self.description,
        "isbn": self.isbn
      }

app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, DateField, IntegerField, SubmitField
from wtforms.validators import DataRequired

class BookForm(FlaskForm):
    title = StringField("Titulo", validators=[DataRequired()])
    author = StringField("Autor", validators=[DataRequired()])
    description = TextAreaField("Descripcción", validators=[DataRequired()])
    pages = IntegerField("# de páginas", validators=[DataRequired()])
    publish_date = DateField("Fecha de publicación", validators=[DataRequired()])
    isbn = StringField("ISBN", validators=[DataRequired()])
    submit = SubmitField("Crear libro")

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from .config import Config
from .routes.book import book_router

def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)
    Bootstrap(app)

    app.register_blueprint(book_router)

    return app

app/routes/book.py
from flask import Blueprint, render_template, flash, redirect, url_for
from app.forms import BookForm
from app.models.book import Book
from app.db import db 

book_router = Blueprint("book_router", __name__)

@book_router.route("/")
def index():
  books = db.books.find()

  return render_template("index.html", books=books)


@book_router.route("/crear", methods=['GET', 'POST'])
def create():
  book_form = BookForm()

  if book_form.validate_on_submit():
      new_book = Book(
        book_form.title.data,
        book_form.author.data,
        book_form.pages.data,
        book_form.publish_date.data,
        book_form.description.data,
        book_form.isbn.data
      )
      # vamos a insertar un documento en la collection books
      db.books.insert_one(new_book.to_json())

      flash("Libro creado correctamente", "success")

      return redirect(url_for('book_router.index'))

  return render_template("create.html", book_form=book_form)

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block body %}
  <div class="container">
    {% for message in get_flashed_messages(category_filter=['success']) %}
    <div class="alert alert-success alert-dismissible">
      <button class="close" data-dismiss="alert">&times;</button>
      {{ message }}
    </div>
    {% endfor %}
    
    {% for message in get_flashed_messages(category_filter=['error'])%}
    <div class="alert alert-danger alert-dismissible">
      <button class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}
    
    {% block content %} {% endblock %}
</div>

{% block scripts %} {{ super() }} {% endblock %}

{% endblock %}

app/templates/create.html
{% extends "base.html" %}

{% block content %}

{% import "bootstrap/wtf.html" as wtf %}

<h1>Crea un libro</h1>

{{ wtf.quick_form(book_form) }}

{% endblock content %}

app/templates/index.html
{% extends "base.html" %} {% block content %}

<h1>Lista de libros</h1>
<a href="{{ url_for('book_router.create') }}"> Crear un libro</a>

<div class="row" style="margin-top: 30px">
  {% for book in books %}
  <div class="col-md-3">
    <div class="panel panel-default">
      <div class="panel-body">
        <h5>{{ book.title }}</h5>
        <p>{{ book.author }}</p>
        <p># de paginas {{ book.pages }}</p>
        <p>{{ book.isbn }}</p>
      </div>
    </div>
  </div>

  {% endfor %}
</div>
{% endblock content %}